# yaml-language-server: $schema=../../router/pkg/config/config.schema.json

version: '1'

authentication:
  jwt:
    jwks:
      - url: https://www.googleapis.com/oauth2/v3/certs
        # Example JWKS - Google OIDC
        refresh_interval: 5m
headers:
  all:
    request:
      - op: 'propagate'
        matching: Authorization
log_level: debug
